data_config:
  train_file: tttt.jsonl
  val_file: dddd.jsonl
  test_file: dddd.jsonl
  num_proc: 1

freezeV: False
max_input_length: 2048  # For Image Must larger than 578
max_output_length: 1024

training_args:
  bf16: True
  # see `transformers.Seq2SeqTrainingArguments`
  output_dir: ./output
  max_steps: 3000
  # needed to be fit for the dataset
  learning_rate: 5e-4
  # settings for data loading
  per_device_train_batch_size: 16
  dataloader_num_workers: 16
  remove_unused_columns: false
  # settings for saving checkpoints
  save_strategy: steps
  save_steps: 500
  # settings for logging
  log_level: info
  logging_strategy: steps
  logging_steps: 10
  # settings for evaluation
  per_device_eval_batch_size: 16
  eval_strategy: steps
  eval_steps: 1000
  # adam_epsilon: 1e-6
  predict_with_generate: true
  generation_config:
    max_new_tokens: 512
peft_config:
  peft_type: LORA
  task_type: CAUSAL_LM
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["q_proj", "k_proj", "v_proj"]
